
import jwt from 'jsonwebtoken';
import dotenv from 'dotenv';
import path from 'path';

// Load env vars
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const secret = process.env.JWT_SECRET;
if (!secret || secret.length < 32) {
    console.error('JWT_SECRET must be set and at least 32 characters.');
    process.exit(1);
}

const payload = {
    sub: '12345678-1234-1234-1234-123456789012', // Fake User ID
    email: 'admin@bypass.com',
    role: 'super_admin', // This is crucial for requireAdmin middleware
    aud: 'authenticated',
    exp: Math.floor(Date.now() / 1000) + (60 * 60 * 24 * 7), // 7 days
};

const token = jwt.sign(payload, secret);

console.log('Generated Bypass Token:');
console.log(token);
